databases:
  - name: postgres
    ipAllowList: []
    databaseName: rails_watch_list
    user: lhb410
    plan: free

services:
  - type: web
    name: rails-watch-list
    env: ruby
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
